spring:
  datasource:
    url: jdbc:oracle:thin:@//193.100.100.225:1521/orcl
    username: CONVERGENCE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: CONVERGENCE
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 6
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小 内存占用优化 提升SQL执行性能
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ;日志是slf4j，log4j改为slf4j
    filters: stat,wall,slf4j
    # ͨ通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

server:
  port: 10002

# 打开sql日志
#logging:
#  level:
#    com.fgi.datasubscriptiontask.dao: debug

# 统计频率（每30分钟）
datasubscription:
  cron:
    expression: 0 0/31 * * * ?





